In [2]:
#import libreria pandas
import pandas as pd


In [9]:
df=pd.DataFrame({'a':[11,21,31],'b':[21,22,23],'c':[31,32,33],'d':[41,42,43]})

df.head()

a   b   c   d
0  11  21  31  41
1  21  22  32  42
2  31  23  33  43

In [4]:
df=pd.DataFrame({'a':[1,2,1],'b':[1,1,1]})
df['a']==1

0     True
1    False
2     True
Name: a, dtype: bool

In [3]:
#Read csv file 
df = pd.read_csv("http://rcs.bu.edu/examples/python/data_analysis/Salaries.csv")


In [4]:
#list first 5 records
df.head()

rank discipline  phd  service   sex  salary
0  Prof          B   56       49  Male  186960
1  Prof          A   12        6  Male   93000
2  Prof          A   23       20  Male  110515
3  Prof          A   40       31  Male  131205
4  Prof          B   20       18  Male  104800

In [5]:
# group data using rank
df_rank = df.groupby(['rank'])

In [6]:
# calculate mean value for each numeric colum per each group
df_rank.mean()

phd    service         salary
rank                                          
AssocProf  15.076923  11.307692   91786.230769
AsstProf    5.052632   2.210526   81362.789474
Prof       27.065217  21.413043  123624.804348

In [7]:
#calcultae mean salary for each professor rank:
df.groupby('rank')[['salary']].mean()

salary
rank                    
AssocProf   91786.230769
AsstProf    81362.789474
Prof       123624.804348

In [11]:
#select only those rows that contain female professors:
df_f = df[df['sex'] == 'Female'] 
df_f.head()

rank discipline  phd  service     sex  salary
39       Prof          B   18       18  Female  129000
40       Prof          A   39       36  Female  137000
41  AssocProf          A   13        8  Female   74830
42   AsstProf          B    4        2  Female   80225
43   AsstProf          B    5        0  Female   77000

In [12]:
# Create a new data frame from the original sorted by the column Salary 
df_sorted = df.sort_values( by ='service') 
df_sorted.head()


rank discipline  phd  service     sex  salary
55  AsstProf          A    2        0  Female   72500
23  AsstProf          A    2        0    Male   85000
43  AsstProf          B    5        0  Female   77000
17  AsstProf          B    4        0    Male   92000
12  AsstProf          B    1        0    Male   88000

In [14]:
#import numpy
import numpy as np


In [2]:
np.dot(np.array([1,-1]),np.array([1,1]))

0

In [4]:
A=np.array([[1,2],[3,4],[5,6],[7,8]])

In [5]:
a=np.array([0,1,0,1,0])

b=np.array([1,0,1,0,1])

a*b

array([0, 0, 0, 0, 0])

In [17]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z) 

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [6]:
a=np.array([0,1])

b=np.array([1,0])

np.dot(a,b)

0

In [7]:
a=np.array([1,1,1,1,1])

a+10

array([11, 11, 11, 11, 11])

In [18]:
#create a vector of size 10 with values ranging from 0 to 1
Z = np.linspace(0,1,12,endpoint=True)[1:-1] 
print(Z) 

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [19]:
#create a ramdon vector of size 10 and sort it
z = np.random.random(10)
z.sort()
print(z)

[0.09439643 0.13406825 0.23591442 0.28350772 0.38368063 0.38808811
 0.53936389 0.70039369 0.81131165 0.82127371]


In [20]:
#How to sum a small array faster than np.sum

# Author: Evgeni Burovski 
Z = np.arange(10)
np.add.reduce(Z)

45

In [22]:
# Print the minimum and maximum representable value for each numpy scalar type 

for dtype in [np.int8, np.int32, np.int64]:    
    print(np.iinfo(dtype).min)    
    print(np.iinfo(dtype).max) 
for dtype in [np.float32, np.float64]:    
    print(np.finfo(dtype).min)    
    print(np.finfo(dtype).max)    
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [ ]:
#Nazareno Medrano 20-12-19